### PR TITLE
Introduced Dojo Octocat in Welcome Module

### PR DESCRIPTION
**Pull request by tom-halpin**
## Proposed changes

In response to https://github.com/dxc-technology/online-devops-dojo/issues/83 introduced Dojo Octocat in Welcome modle

## Types of changes

What types of changes does your code introduce to Online DevOps Dojo?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Workflow change
- [X] Documentation update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [X] I have read the [CONTRIBUTING](https://github.com/dxc-technology/online-devops-dojo/blob/master/CONTRIBUTING.md) doc.
- [X ] Lint passes locally with my changes.
- [X] I have added necessary documentation (if appropriate).
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by pberthonneau — CHANGES_REQUESTED** [review]
People are not free to take modules in any order. I had precised in the intro of few modules that they depend on others (and not only on welcome).

**Review by adamdmharvey — CHANGES_REQUESTED** [review]
He's a cool cat.  😆    Note, the `octocat.gif` is not used in the PR; is it needed?

**Comment by tom-halpin** [comment]
> People are not free to take modules in any order. I had precised in the intro of few modules that they depend on others (and not only on welcome).

ok I will correct that note

**Comment by tom-halpin** [comment]
> He's a cool cat. 😆 Note, the `octocat.gif` is not used in the PR; is it needed?



> He's a cool cat. 😆 Note, the `octocat.gif` is not used in the PR; is it needed?

the original format is gif, but most of the images in the dojo are png so included both for completeness

**Comment by tom-halpin** [comment]
> > People are not free to take modules in any order. I had precised in the intro of few modules that they depend on others (and not only on welcome).
> 
> ok I will correct that note

done

**Comment by tom-halpin** [comment]
> > He's a cool cat. 😆 Note, the `octocat.gif` is not used in the PR; is it needed?
> 
> > He's a cool cat. 😆 Note, the `octocat.gif` is not used in the PR; is it needed?
> 
> the original format is gif, but most of the images in the dojo are png so included both for completeness

done

**Review by adamdmharvey — APPROVED** [review]

**Review by pberthonneau — APPROVED** [review]

**Pull request merged**
