### PR TITLE
Fixed issue running prepare.sh in version control module

### PR DESCRIPTION
**Pull request by tom-halpin**
## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to Online DevOps Dojo?
_Put an `x` in the boxes that apply_

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Workflow change
- [ ] Documentation update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/dxc-technology/online-devops-dojo/blob/master/CONTRIBUTING.md) doc.
- [ ] Lint passes locally with my changes.
- [ ] I have added necessary documentation (if appropriate).
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by tom-halpin** [comment]
@ojacques @pberthonneau this is to address https://github.com/dxc-technology/online-devops-dojo/issues/94

**Review by pberthonneau — COMMENTED** [review]
Hi Tom

It seems a change on Katacoda side. I already had in that past such default change, then fixed by Ben.

prepare.sh goes into `~/` (which is currently /root) and not /root/pet-clinic
{ "file": "prepare.sh", "target": "~/","chmod": "+x" }

Curious, after running prepare.sh it vanishes.

We have the exact same setting on continuous integration and prepare.sh lands in /root

Then I think about a Katacoda config issue.
Else a workaround could be to change
    "uieditorpath":"/root/pet-clinic",
into
    "uieditorpath":"/root",

**Comment by tom-halpin** [comment]
@pberthonneau I observed the same behaviors, and suspected this was a Katacoda change. I also thought about changing the uieditorpath setting, but thought the change I proposed was the one that had the smallest risk of unwanted side effects

**Review by pberthonneau — APPROVED** [review]
Go ahead but there is a risk that the behavior reverts to what it was if Katacoda fixes their issue.

**Pull request merged**
